package com.example.testproject;

import android.graphics.Color;
import android.util.Log;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Locale;

import org.opencv.core.Core;
import org.opencv.core.CvType;
import org.opencv.core.Mat;
import org.opencv.core.MatOfPoint;
import org.opencv.core.Scalar;
import org.opencv.imgproc.Imgproc;

public class GetColorName {
    private static boolean flag = false;

    /** Initialize color list */
    /** data from: https://xkcd.com/color/rgb.txt */

    public static HashMap<String, String> ColorName = new HashMap<String, String>();
    static {
        ColorName.put("acc2d9", "cloudy blue");
        ColorName.put("56ae57", "dark pastel green");
        ColorName.put("b2996e", "dust");
        ColorName.put("a8ff04", "electric lime");
        ColorName.put("69d84f", "fresh green");
        ColorName.put("894585", "light eggplant");
        ColorName.put("70b23f", "nasty green");
        ColorName.put("d4ffff", "really light blue");
        ColorName.put("65ab7c", "tea");
        ColorName.put("952e8f", "warm purple");
        ColorName.put("fcfc81", "yellowish tan");
        ColorName.put("a5a391", "cement");
        ColorName.put("388004", "dark grass green");
        ColorName.put("4c9085", "dusty teal");
        ColorName.put("5e9b8a", "grey teal");
        ColorName.put("efb435", "macaroni and cheese");
        ColorName.put("d99b82", "pinkish tan");
        ColorName.put("0a5f38", "spruce");
        ColorName.put("0c06f7", "strong blue");
        ColorName.put("61de2a", "toxic green");
        ColorName.put("3778bf", "windows blue");
        ColorName.put("2242c7", "blue blue");
        ColorName.put("533cc6", "blue with a hint of purple");
        ColorName.put("9bb53c", "booger");
        ColorName.put("05ffa6", "bright sea green");
        ColorName.put("1f6357", "dark green blue");
        ColorName.put("017374", "deep turquoise");
        ColorName.put("0cb577", "green teal");
        ColorName.put("ff0789", "strong pink");
        ColorName.put("afa88b", "bland");
        ColorName.put("08787f", "deep aqua");
        ColorName.put("dd85d7", "lavender pink");
        ColorName.put("a6c875", "light moss green");
        ColorName.put("a7ffb5", "light seafoam green");
        ColorName.put("c2b709", "olive yellow");
        ColorName.put("e78ea5", "pig pink");
        ColorName.put("966ebd", "deep lilac");
        ColorName.put("ccad60", "desert");
        ColorName.put("ac86a8", "dusty lavender");
        ColorName.put("947e94", "purpley grey");
        ColorName.put("983fb2", "purply");
        ColorName.put("ff63e9", "candy pink");
        ColorName.put("b2fba5", "light pastel green");
        ColorName.put("63b365", "boring green");
        ColorName.put("8ee53f", "kiwi green");
        ColorName.put("b7e1a1", "light grey green");
        ColorName.put("ff6f52", "orange pink");
        ColorName.put("bdf8a3", "tea green");
        ColorName.put("d3b683", "very light brown");
        ColorName.put("fffcc4", "egg shell");
        ColorName.put("430541", "eggplant purple");
        ColorName.put("ffb2d0", "powder pink");
        ColorName.put("997570", "reddish grey");
        ColorName.put("ad900d", "light dirty brown");
        ColorName.put("c48efd", "liliac");
        ColorName.put("507b9c", "stormy blue");
        ColorName.put("fffd78", "custard");
        ColorName.put("da467d", "darkish pink");
        ColorName.put("410200", "deep brown");
        ColorName.put("c9d179", "greenish beige");
        ColorName.put("fffa86", "manilla");
        ColorName.put("5684ae", "off blue");
        ColorName.put("6b7c85", "battleship grey");
        ColorName.put("6f6c0a", "browny green");
        ColorName.put("7e4071", "bruise");
        ColorName.put("009337", "kelley green");
        ColorName.put("d0e429", "sickly yellow");
        ColorName.put("fff917", "sunny yellow");
        ColorName.put("1d5dec", "azul");
        ColorName.put("054907", "darkgreen");
        ColorName.put("b5ce08", "green/yellow");
        ColorName.put("8fb67b", "lichen");
        ColorName.put("c8ffb0", "light light green");
        ColorName.put("fdde6c", "pale gold");
        ColorName.put("ffdf22", "sun yellow");
        ColorName.put("a9be70", "tan green");
        ColorName.put("6832e3", "burple");
        ColorName.put("fdb147", "butterscotch");
        ColorName.put("c7ac7d", "toupe");
        ColorName.put("fff39a", "dark cream");
        ColorName.put("850e04", "indian red");
        ColorName.put("efc0fe", "light lavendar");
        ColorName.put("40fd14", "poison green");
        ColorName.put("b6c406", "baby puke green");
        ColorName.put("9dff00", "bright yellow green");
        ColorName.put("3c4142", "charcoal grey");
        ColorName.put("f2ab15", "squash");
        ColorName.put("ac4f06", "cinnamon");
        ColorName.put("c4fe82", "light pea green");
        ColorName.put("2cfa1f", "radioactive green");
        ColorName.put("9a6200", "raw sienna");
        ColorName.put("ca9bf7", "baby purple");
        ColorName.put("875f42", "cocoa");
        ColorName.put("3a2efe", "light royal blue");
        ColorName.put("fd8d49", "orangeish");
        ColorName.put("8b3103", "rust brown");
        ColorName.put("cba560", "sand brown");
        ColorName.put("698339", "swamp");
        ColorName.put("0cdc73", "tealish green");
        ColorName.put("b75203", "burnt siena");
        ColorName.put("7f8f4e", "camo");
        ColorName.put("26538d", "dusk blue");
        ColorName.put("63a950", "fern");
        ColorName.put("c87f89", "old rose");
        ColorName.put("b1fc99", "pale light green");
        ColorName.put("ff9a8a", "peachy pink");
        ColorName.put("f6688e", "rosy pink");
        ColorName.put("76fda8", "light bluish green");
        ColorName.put("53fe5c", "light bright green");
        ColorName.put("4efd54", "light neon green");
        ColorName.put("a0febf", "light seafoam");
        ColorName.put("7bf2da", "tiffany blue");
        ColorName.put("bcf5a6", "washed out green");
        ColorName.put("ca6b02", "browny orange");
        ColorName.put("107ab0", "nice blue");
        ColorName.put("2138ab", "sapphire");
        ColorName.put("719f91", "greyish teal");
        ColorName.put("fdb915", "orangey yellow");
        ColorName.put("fefcaf", "parchment");
        ColorName.put("fcf679", "straw");
        ColorName.put("1d0200", "very dark brown");
        ColorName.put("cb6843", "terracota");
        ColorName.put("247afd", "clear blue");
        ColorName.put("ffffb6", "creme");
        ColorName.put("90fda9", "foam green");
        ColorName.put("86a17d", "grey/green");
        ColorName.put("fddc5c", "light gold");
        ColorName.put("78d1b6", "seafoam blue");
        ColorName.put("13bbaf", "topaz");
        ColorName.put("fb5ffc", "violet pink");
        ColorName.put("20f986", "wintergreen");
        ColorName.put("ffe36e", "yellow tan");
        ColorName.put("9d0759", "dark fuchsia");
        ColorName.put("3a18b1", "indigo blue");
        ColorName.put("c2ff89", "light yellowish green");
        ColorName.put("d767ad", "pale magenta");
        ColorName.put("720058", "rich purple");
        ColorName.put("ffda03", "sunflower yellow");
        ColorName.put("01c08d", "green/blue");
        ColorName.put("ac7434", "leather");
        ColorName.put("014600", "racing green");
        ColorName.put("9900fa", "vivid purple");
        ColorName.put("02066f", "dark royal blue");
        ColorName.put("8e7618", "hazel");
        ColorName.put("d1768f", "muted pink");
        ColorName.put("96b403", "booger green");
        ColorName.put("fdff63", "canary");
        ColorName.put("95a3a6", "cool grey");
        ColorName.put("7f684e", "dark taupe");
        ColorName.put("751973", "darkish purple");
        ColorName.put("089404", "true green");
        ColorName.put("ff6163", "coral pink");
        ColorName.put("598556", "dark sage");
        ColorName.put("214761", "dark slate blue");
        ColorName.put("3c73a8", "flat blue");
        ColorName.put("ba9e88", "mushroom");
        ColorName.put("021bf9", "rich blue");
        ColorName.put("734a65", "dirty purple");
        ColorName.put("23c48b", "greenblue");
        ColorName.put("8fae22", "icky green");
        ColorName.put("e6f2a2", "light khaki");
        ColorName.put("4b57db", "warm blue");
        ColorName.put("d90166", "dark hot pink");
        ColorName.put("015482", "deep sea blue");
        ColorName.put("9d0216", "carmine");
        ColorName.put("728f02", "dark yellow green");
        ColorName.put("ffe5ad", "pale peach");
        ColorName.put("4e0550", "plum purple");
        ColorName.put("f9bc08", "golden rod");
        ColorName.put("ff073a", "neon red");
        ColorName.put("c77986", "old pink");
        ColorName.put("d6fffe", "very pale blue");
        ColorName.put("fe4b03", "blood orange");
        ColorName.put("fd5956", "grapefruit");
        ColorName.put("fce166", "sand yellow");
        ColorName.put("b2713d", "clay brown");
        ColorName.put("1f3b4d", "dark blue grey");
        ColorName.put("699d4c", "flat green");
        ColorName.put("56fca2", "light green blue");
        ColorName.put("fb5581", "warm pink");
        ColorName.put("3e82fc", "dodger blue");
        ColorName.put("a0bf16", "gross green");
        ColorName.put("d6fffa", "ice");
        ColorName.put("4f738e", "metallic blue");
        ColorName.put("ffb19a", "pale salmon");
        ColorName.put("5c8b15", "sap green");
        ColorName.put("54ac68", "algae");
        ColorName.put("89a0b0", "bluey grey");
        ColorName.put("7ea07a", "greeny grey");
        ColorName.put("1bfc06", "highlighter green");
        ColorName.put("cafffb", "light light blue");
        ColorName.put("b6ffbb", "light mint");
        ColorName.put("a75e09", "raw umber");
        ColorName.put("152eff", "vivid blue");
        ColorName.put("8d5eb7", "deep lavender");
        ColorName.put("5f9e8f", "dull teal");
        ColorName.put("63f7b4", "light greenish blue");
        ColorName.put("606602", "mud green");
        ColorName.put("fc86aa", "pinky");
        ColorName.put("8c0034", "red wine");
        ColorName.put("758000", "dark avocado green");
        ColorName.put("ab7e4c", "tan brown");
        ColorName.put("030764", "darkblue");
        ColorName.put("fe86a4", "rosa");
        ColorName.put("d5174e", "lipstick");
        ColorName.put("fed0fc", "pale mauve");
        ColorName.put("680018", "claret");
        ColorName.put("fedf08", "dandelion");
        ColorName.put("fe420f", "orangered");
        ColorName.put("6f7c00", "poop green");
        ColorName.put("ca0147", "ruby");
        ColorName.put("1b2431", "dark");
        ColorName.put("00fbb0", "greenish turquoise");
        ColorName.put("db5856", "pastel red");
        ColorName.put("ddd618", "piss yellow");
        ColorName.put("41fdfe", "bright cyan");
        ColorName.put("cf524e", "dark coral");
        ColorName.put("21c36f", "algae green");
        ColorName.put("a90308", "darkish red");
        ColorName.put("6e1005", "reddy brown");
        ColorName.put("fe828c", "blush pink");
        ColorName.put("4b6113", "camouflage green");
        ColorName.put("4da409", "lawn green");
        ColorName.put("beae8a", "putty");
        ColorName.put("0339f8", "vibrant blue");
        ColorName.put("a88f59", "dark sand");
        ColorName.put("5d21d0", "purple/blue");
        ColorName.put("feb209", "saffron");
        ColorName.put("4e518b", "twilight");
        ColorName.put("964e02", "warm brown");
        ColorName.put("85a3b2", "bluegrey");
        ColorName.put("ff69af", "bubble gum pink");
        ColorName.put("c3fbf4", "duck egg blue");
        ColorName.put("2afeb7", "greenish cyan");
        ColorName.put("005f6a", "petrol");
        ColorName.put("0c1793", "royal");
        ColorName.put("ffff81", "butter");
        ColorName.put("f0833a", "dusty orange");
        ColorName.put("f1f33f", "off yellow");
        ColorName.put("b1d27b", "pale olive green");
        ColorName.put("fc824a", "orangish");
        ColorName.put("71aa34", "leaf");
        ColorName.put("b7c9e2", "light blue grey");
        ColorName.put("4b0101", "dried blood");
        ColorName.put("a552e6", "lightish purple");
        ColorName.put("af2f0d", "rusty red");
        ColorName.put("8b88f8", "lavender blue");
        ColorName.put("9af764", "light grass green");
        ColorName.put("a6fbb2", "light mint green");
        ColorName.put("ffc512", "sunflower");
        ColorName.put("750851", "velvet");
        ColorName.put("c14a09", "brick orange");
        ColorName.put("fe2f4a", "lightish red");
        ColorName.put("0203e2", "pure blue");
        ColorName.put("0a437a", "twilight blue");
        ColorName.put("a50055", "violet red");
        ColorName.put("ae8b0c", "yellowy brown");
        ColorName.put("fd798f", "carnation");
        ColorName.put("bfac05", "muddy yellow");
        ColorName.put("3eaf76", "dark seafoam green");
        ColorName.put("c74767", "deep rose");
        ColorName.put("b9484e", "dusty red");
        ColorName.put("647d8e", "grey/blue");
        ColorName.put("bffe28", "lemon lime");
        ColorName.put("d725de", "purple/pink");
        ColorName.put("b29705", "brown yellow");
        ColorName.put("673a3f", "purple brown");
        ColorName.put("a87dc2", "wisteria");
        ColorName.put("fafe4b", "banana yellow");
        ColorName.put("c0022f", "lipstick red");
        ColorName.put("0e87cc", "water blue");
        ColorName.put("8d8468", "brown grey");
        ColorName.put("ad03de", "vibrant purple");
        ColorName.put("8cff9e", "baby green");
        ColorName.put("94ac02", "barf green");
        ColorName.put("c4fff7", "eggshell blue");
        ColorName.put("fdee73", "sandy yellow");
        ColorName.put("33b864", "cool green");
        ColorName.put("fff9d0", "pale");
        ColorName.put("758da3", "blue/grey");
        ColorName.put("f504c9", "hot magenta");
        ColorName.put("77a1b5", "greyblue");
        ColorName.put("8756e4", "purpley");
        ColorName.put("c27e79", "brownish pink");
        ColorName.put("017371", "dark aquamarine");
        ColorName.put("9f8303", "diarrhea");
        ColorName.put("f7d560", "light mustard");
        ColorName.put("bdf6fe", "pale sky blue");
        ColorName.put("75b84f", "turtle green");
        ColorName.put("9cbb04", "bright olive");
        ColorName.put("29465b", "dark grey blue");
        ColorName.put("696006", "greeny brown");
        ColorName.put("adf802", "lemon green");
        ColorName.put("c1c6fc", "light periwinkle");
        ColorName.put("35ad6b", "seaweed green");
        ColorName.put("fffd37", "sunshine yellow");
        ColorName.put("f36196", "medium pink");
        ColorName.put("947706", "puke brown");
        ColorName.put("fff4f2", "very light pink");
        ColorName.put("1e9167", "viridian");
        ColorName.put("b5c306", "bile");
        ColorName.put("feff7f", "faded yellow");
        ColorName.put("cffdbc", "very pale green");
        ColorName.put("0add08", "vibrant green");
        ColorName.put("87fd05", "bright lime");
        ColorName.put("1ef876", "spearmint");
        ColorName.put("7bfdc7", "light aquamarine");
        ColorName.put("bcecac", "light sage");
        ColorName.put("bbf90f", "yellowgreen");
        ColorName.put("ab9004", "baby poo");
        ColorName.put("1fb57a", "dark seafoam");
        ColorName.put("00555a", "deep teal");
        ColorName.put("a484ac", "heather");
        ColorName.put("c45508", "rust orange");
        ColorName.put("3f829d", "dirty blue");
        ColorName.put("548d44", "fern green");
        ColorName.put("c95efb", "bright lilac");
        ColorName.put("3ae57f", "weird green");
        ColorName.put("016795", "peacock blue");
        ColorName.put("87a922", "avocado green");
        ColorName.put("f0944d", "faded orange");
        ColorName.put("5d1451", "grape purple");
        ColorName.put("25ff29", "hot green");
        ColorName.put("d0fe1d", "lime yellow");
        ColorName.put("ffa62b", "mango");
        ColorName.put("01b44c", "shamrock");
        ColorName.put("ff6cb5", "bubblegum");
        ColorName.put("6b4247", "purplish brown");
        ColorName.put("c7c10c", "vomit yellow");
        ColorName.put("b7fffa", "pale cyan");
        ColorName.put("aeff6e", "key lime");
        ColorName.put("ec2d01", "tomato red");
        ColorName.put("76ff7b", "lightgreen");
        ColorName.put("730039", "merlot");
        ColorName.put("040348", "night blue");
        ColorName.put("df4ec8", "purpleish pink");
        ColorName.put("6ecb3c", "apple");
        ColorName.put("8f9805", "baby poop green");
        ColorName.put("5edc1f", "green apple");
        ColorName.put("d94ff5", "heliotrope");
        ColorName.put("c8fd3d", "yellow/green");
        ColorName.put("070d0d", "almost black");
        ColorName.put("4984b8", "cool blue");
        ColorName.put("51b73b", "leafy green");
        ColorName.put("ac7e04", "mustard brown");
        ColorName.put("4e5481", "dusk");
        ColorName.put("876e4b", "dull brown");
        ColorName.put("58bc08", "frog green");
        ColorName.put("2fef10", "vivid green");
        ColorName.put("2dfe54", "bright light green");
        ColorName.put("0aff02", "fluro green");
        ColorName.put("9cef43", "kiwi");
        ColorName.put("18d17b", "seaweed");
        ColorName.put("35530a", "navy green");
        ColorName.put("1805db", "ultramarine blue");
        ColorName.put("6258c4", "iris");
        ColorName.put("ff964f", "pastel orange");
        ColorName.put("ffab0f", "yellowish orange");
        ColorName.put("8f8ce7", "perrywinkle");
        ColorName.put("24bca8", "tealish");
        ColorName.put("3f012c", "dark plum");
        ColorName.put("cbf85f", "pear");
        ColorName.put("ff724c", "pinkish orange");
        ColorName.put("280137", "midnight purple");
        ColorName.put("b36ff6", "light urple");
        ColorName.put("48c072", "dark mint");
        ColorName.put("bccb7a", "greenish tan");
        ColorName.put("a8415b", "light burgundy");
        ColorName.put("06b1c4", "turquoise blue");
        ColorName.put("f1da7a", "sandy");
        ColorName.put("ff0490", "electric pink");
        ColorName.put("805b87", "muted purple");
        ColorName.put("50a747", "mid green");
        ColorName.put("a8a495", "greyish");
        ColorName.put("cfff04", "neon yellow");
        ColorName.put("ffff7e", "banana");
        ColorName.put("ff7fa7", "carnation pink");
        ColorName.put("ef4026", "tomato");
        ColorName.put("3c9992", "sea");
        ColorName.put("886806", "muddy brown");
        ColorName.put("04f489", "turquoise green");
        ColorName.put("fef69e", "buff");
        ColorName.put("cfaf7b", "fawn");
        ColorName.put("3b719f", "muted blue");
        ColorName.put("fdc1c5", "pale rose");
        ColorName.put("20c073", "dark mint green");
        ColorName.put("9b5fc0", "amethyst");
        ColorName.put("0f9b8e", "blue/green");
        ColorName.put("742802", "chestnut");
        ColorName.put("9db92c", "sick green");
        ColorName.put("a4bf20", "pea");
        ColorName.put("cd5909", "rusty orange");
        ColorName.put("ada587", "stone");
        ColorName.put("be013c", "rose red");
        ColorName.put("b8ffeb", "pale aqua");
        ColorName.put("dc4d01", "deep orange");
        ColorName.put("a2653e", "earth");
        ColorName.put("638b27", "mossy green");
        ColorName.put("419c03", "grassy green");
        ColorName.put("b1ff65", "pale lime green");
        ColorName.put("9dbcd4", "light grey blue");
        ColorName.put("fdfdfe", "pale grey");
        ColorName.put("77ab56", "asparagus");
        ColorName.put("464196", "blueberry");
        ColorName.put("990147", "purple red");
        ColorName.put("befd73", "pale lime");
        ColorName.put("32bf84", "greenish teal");
        ColorName.put("af6f09", "caramel");
        ColorName.put("a0025c", "deep magenta");
        ColorName.put("ffd8b1", "light peach");
        ColorName.put("7f4e1e", "milk chocolate");
        ColorName.put("bf9b0c", "ocher");
        ColorName.put("6ba353", "off green");
        ColorName.put("f075e6", "purply pink");
        ColorName.put("7bc8f6", "lightblue");
        ColorName.put("475f94", "dusky blue");
        ColorName.put("f5bf03", "golden");
        ColorName.put("fffeb6", "light beige");
        ColorName.put("fffd74", "butter yellow");
        ColorName.put("895b7b", "dusky purple");
        ColorName.put("436bad", "french blue");
        ColorName.put("c6f808", "greeny yellow");
        ColorName.put("f43605", "orangish red");
        ColorName.put("02c14d", "shamrock green");
        ColorName.put("b25f03", "orangish brown");
        ColorName.put("2a7e19", "tree green");
        ColorName.put("490648", "deep violet");
        ColorName.put("536267", "gunmetal");
        ColorName.put("5a06ef", "blue/purple");
        ColorName.put("cf0234", "cherry");
        ColorName.put("c4a661", "sandy brown");
        ColorName.put("978a84", "warm grey");
        ColorName.put("1f0954", "dark indigo");
        ColorName.put("03012d", "midnight");
        ColorName.put("2bb179", "bluey green");
        ColorName.put("c3909b", "grey pink");
        ColorName.put("a66fb5", "soft purple");
        ColorName.put("770001", "blood");
        ColorName.put("922b05", "brown red");
        ColorName.put("7d7f7c", "medium grey");
        ColorName.put("990f4b", "berry");
        ColorName.put("8f7303", "poo");
        ColorName.put("c83cb9", "purpley pink");
        ColorName.put("fea993", "light salmon");
        ColorName.put("acbb0d", "snot");
        ColorName.put("c071fe", "easter purple");
        ColorName.put("ccfd7f", "light yellow green");
        ColorName.put("00022e", "dark navy blue");
        ColorName.put("828344", "drab");
        ColorName.put("ffc5cb", "light rose");
        ColorName.put("ab1239", "rouge");
        ColorName.put("b0054b", "purplish red");
        ColorName.put("99cc04", "slime green");
        ColorName.put("937c00", "baby poop");
        ColorName.put("019529", "irish green");
        ColorName.put("ef1de7", "pink/purple");
        ColorName.put("000435", "dark navy");
        ColorName.put("42b395", "greeny blue");
        ColorName.put("9d5783", "light plum");
        ColorName.put("c8aca9", "pinkish grey");
        ColorName.put("c87606", "dirty orange");
        ColorName.put("aa2704", "rust red");
        ColorName.put("e4cbff", "pale lilac");
        ColorName.put("fa4224", "orangey red");
        ColorName.put("0804f9", "primary blue");
        ColorName.put("5cb200", "kermit green");
        ColorName.put("76424e", "brownish purple");
        ColorName.put("6c7a0e", "murky green");
        ColorName.put("fbdd7e", "wheat");
        ColorName.put("2a0134", "very dark purple");
        ColorName.put("044a05", "bottle green");
        ColorName.put("fd4659", "watermelon");
        ColorName.put("0d75f8", "deep sky blue");
        ColorName.put("fe0002", "fire engine red");
        ColorName.put("cb9d06", "yellow ochre");
        ColorName.put("fb7d07", "pumpkin orange");
        ColorName.put("b9cc81", "pale olive");
        ColorName.put("edc8ff", "light lilac");
        ColorName.put("61e160", "lightish green");
        ColorName.put("8ab8fe", "carolina blue");
        ColorName.put("920a4e", "mulberry");
        ColorName.put("fe02a2", "shocking pink");
        ColorName.put("9a3001", "auburn");
        ColorName.put("65fe08", "bright lime green");
        ColorName.put("befdb7", "celadon");
        ColorName.put("b17261", "pinkish brown");
        ColorName.put("885f01", "poo brown");
        ColorName.put("02ccfe", "bright sky blue");
        ColorName.put("c1fd95", "celery");
        ColorName.put("836539", "dirt brown");
        ColorName.put("fb2943", "strawberry");
        ColorName.put("84b701", "dark lime");
        ColorName.put("b66325", "copper");
        ColorName.put("7f5112", "medium brown");
        ColorName.put("5fa052", "muted green");
        ColorName.put("6dedfd", "robin's egg");
        ColorName.put("0bf9ea", "bright aqua");
        ColorName.put("c760ff", "bright lavender");
        ColorName.put("ffffcb", "ivory");
        ColorName.put("f6cefc", "very light purple");
        ColorName.put("155084", "light navy");
        ColorName.put("f5054f", "pink red");
        ColorName.put("645403", "olive brown");
        ColorName.put("7a5901", "poop brown");
        ColorName.put("a8b504", "mustard green");
        ColorName.put("3d9973", "ocean green");
        ColorName.put("000133", "very dark blue");
        ColorName.put("76a973", "dusty green");
        ColorName.put("2e5a88", "light navy blue");
        ColorName.put("0bf77d", "minty green");
        ColorName.put("bd6c48", "adobe");
        ColorName.put("ac1db8", "barney");
        ColorName.put("2baf6a", "jade green");
        ColorName.put("26f7fd", "bright light blue");
        ColorName.put("aefd6c", "light lime");
        ColorName.put("9b8f55", "dark khaki");
        ColorName.put("ffad01", "orange yellow");
        ColorName.put("c69c04", "ocre");
        ColorName.put("f4d054", "maize");
        ColorName.put("de9dac", "faded pink");
        ColorName.put("05480d", "british racing green");
        ColorName.put("c9ae74", "sandstone");
        ColorName.put("60460f", "mud brown");
        ColorName.put("98f6b0", "light sea green");
        ColorName.put("8af1fe", "robin egg blue");
        ColorName.put("2ee8bb", "aqua marine");
        ColorName.put("11875d", "dark sea green");
        ColorName.put("fdb0c0", "soft pink");
        ColorName.put("b16002", "orangey brown");
        ColorName.put("f7022a", "cherry red");
        ColorName.put("d5ab09", "burnt yellow");
        ColorName.put("86775f", "brownish grey");
        ColorName.put("c69f59", "camel");
        ColorName.put("7a687f", "purplish grey");
        ColorName.put("042e60", "marine");
        ColorName.put("c88d94", "greyish pink");
        ColorName.put("a5fbd5", "pale turquoise");
        ColorName.put("fffe71", "pastel yellow");
        ColorName.put("6241c7", "bluey purple");
        ColorName.put("fffe40", "canary yellow");
        ColorName.put("d3494e", "faded red");
        ColorName.put("985e2b", "sepia");
        ColorName.put("a6814c", "coffee");
        ColorName.put("ff08e8", "bright magenta");
        ColorName.put("9d7651", "mocha");
        ColorName.put("feffca", "ecru");
        ColorName.put("98568d", "purpleish");
        ColorName.put("9e003a", "cranberry");
        ColorName.put("287c37", "darkish green");
        ColorName.put("b96902", "brown orange");
        ColorName.put("ba6873", "dusky rose");
        ColorName.put("ff7855", "melon");
        ColorName.put("94b21c", "sickly green");
        ColorName.put("c5c9c7", "silver");
        ColorName.put("661aee", "purply blue");
        ColorName.put("6140ef", "purpleish blue");
        ColorName.put("9be5aa", "hospital green");
        ColorName.put("7b5804", "dirty brown");
        ColorName.put("276ab3", "mid blue");
        ColorName.put("feb308", "amber");
        ColorName.put("8cfd7e", "easter green");
        ColorName.put("6488ea", "soft blue");
        ColorName.put("056eee", "cerulean blue");
        ColorName.put("b27a01", "golden brown");
        ColorName.put("0ffef9", "bright turquoise");
        ColorName.put("fa2a55", "red pink");
        ColorName.put("820747", "red purple");
        ColorName.put("7a6a4f", "greyish brown");
        ColorName.put("f4320c", "vermillion");
        ColorName.put("a13905", "russet");
        ColorName.put("6f828a", "steel grey");
        ColorName.put("a55af4", "lighter purple");
        ColorName.put("ad0afd", "bright violet");
        ColorName.put("004577", "prussian blue");
        ColorName.put("658d6d", "slate green");
        ColorName.put("ca7b80", "dirty pink");
        ColorName.put("005249", "dark blue green");
        ColorName.put("2b5d34", "pine");
        ColorName.put("bff128", "yellowy green");
        ColorName.put("b59410", "dark gold");
        ColorName.put("2976bb", "bluish");
        ColorName.put("014182", "darkish blue");
        ColorName.put("bb3f3f", "dull red");
        ColorName.put("fc2647", "pinky red");
        ColorName.put("a87900", "bronze");
        ColorName.put("82cbb2", "pale teal");
        ColorName.put("667c3e", "military green");
        ColorName.put("fe46a5", "barbie pink");
        ColorName.put("fe83cc", "bubblegum pink");
        ColorName.put("94a617", "pea soup green");
        ColorName.put("a88905", "dark mustard");
        ColorName.put("9e43a2", "medium purple");
        ColorName.put("062e03", "very dark green");
        ColorName.put("8a6e45", "dirt");
        ColorName.put("cc7a8b", "dusky pink");
        ColorName.put("9e0168", "red violet");
        ColorName.put("fdff38", "lemon yellow");
        ColorName.put("c0fa8b", "pistachio");
        ColorName.put("eedc5b", "dull yellow");
        ColorName.put("7ebd01", "dark lime green");
        ColorName.put("3b5b92", "denim blue");
        ColorName.put("01889f", "teal blue");
        ColorName.put("3d7afd", "lightish blue");
        ColorName.put("5f34e7", "purpley blue");
        ColorName.put("6d5acf", "light indigo");
        ColorName.put("748500", "swamp green");
        ColorName.put("706c11", "brown green");
        ColorName.put("3c0008", "dark maroon");
        ColorName.put("cb00f5", "hot purple");
        ColorName.put("002d04", "dark forest green");
        ColorName.put("658cbb", "faded blue");
        ColorName.put("749551", "drab green");
        ColorName.put("b9ff66", "light lime green");
        ColorName.put("9dc100", "snot green");
        ColorName.put("faee66", "yellowish");
        ColorName.put("7efbb3", "light blue green");
        ColorName.put("7b002c", "bordeaux");
        ColorName.put("c292a1", "light mauve");
        ColorName.put("017b92", "ocean");
        ColorName.put("fcc006", "marigold");
        ColorName.put("657432", "muddy green");
        ColorName.put("d8863b", "dull orange");
        ColorName.put("738595", "steel");
        ColorName.put("aa23ff", "electric purple");
        ColorName.put("08ff08", "fluorescent green");
        ColorName.put("9b7a01", "yellowish brown");
        ColorName.put("f29e8e", "blush");
        ColorName.put("6fc276", "soft green");
        ColorName.put("ff5b00", "bright orange");
        ColorName.put("fdff52", "lemon");
        ColorName.put("866f85", "purple grey");
        ColorName.put("8ffe09", "acid green");
        ColorName.put("eecffe", "pale lavender");
        ColorName.put("510ac9", "violet blue");
        ColorName.put("4f9153", "light forest green");
        ColorName.put("9f2305", "burnt red");
        ColorName.put("728639", "khaki green");
        ColorName.put("de0c62", "cerise");
        ColorName.put("916e99", "faded purple");
        ColorName.put("ffb16d", "apricot");
        ColorName.put("3c4d03", "dark olive green");
        ColorName.put("7f7053", "grey brown");
        ColorName.put("77926f", "green grey");
        ColorName.put("010fcc", "true blue");
        ColorName.put("ceaefa", "pale violet");
        ColorName.put("8f99fb", "periwinkle blue");
        ColorName.put("c6fcff", "light sky blue");
        ColorName.put("5539cc", "blurple");
        ColorName.put("544e03", "green brown");
        ColorName.put("017a79", "bluegreen");
        ColorName.put("01f9c6", "bright teal");
        ColorName.put("c9b003", "brownish yellow");
        ColorName.put("929901", "pea soup");
        ColorName.put("0b5509", "forest");
        ColorName.put("a00498", "barney purple");
        ColorName.put("2000b1", "ultramarine");
        ColorName.put("94568c", "purplish");
        ColorName.put("c2be0e", "puke yellow");
        ColorName.put("748b97", "bluish grey");
        ColorName.put("665fd1", "dark periwinkle");
        ColorName.put("9c6da5", "dark lilac");
        ColorName.put("c44240", "reddish");
        ColorName.put("a24857", "light maroon");
        ColorName.put("825f87", "dusty purple");
        ColorName.put("c9643b", "terra cotta");
        ColorName.put("90b134", "avocado");
        ColorName.put("01386a", "marine blue");
        ColorName.put("25a36f", "teal green");
        ColorName.put("59656d", "slate grey");
        ColorName.put("75fd63", "lighter green");
        ColorName.put("21fc0d", "electric green");
        ColorName.put("5a86ad", "dusty blue");
        ColorName.put("fec615", "golden yellow");
        ColorName.put("fffd01", "bright yellow");
        ColorName.put("dfc5fe", "light lavender");
        ColorName.put("b26400", "umber");
        ColorName.put("7f5e00", "poop");
        ColorName.put("de7e5d", "dark peach");
        ColorName.put("048243", "jungle green");
        ColorName.put("ffffd4", "eggshell");
        ColorName.put("3b638c", "denim");
        ColorName.put("b79400", "yellow brown");
        ColorName.put("84597e", "dull purple");
        ColorName.put("411900", "chocolate brown");
        ColorName.put("7b0323", "wine red");
        ColorName.put("04d9ff", "neon blue");
        ColorName.put("667e2c", "dirty green");
        ColorName.put("fbeeac", "light tan");
        ColorName.put("d7fffe", "ice blue");
        ColorName.put("4e7496", "cadet blue");
        ColorName.put("874c62", "dark mauve");
        ColorName.put("d5ffff", "very light blue");
        ColorName.put("826d8c", "grey purple");
        ColorName.put("ffbacd", "pastel pink");
        ColorName.put("d1ffbd", "very light green");
        ColorName.put("448ee4", "dark sky blue");
        ColorName.put("05472a", "evergreen");
        ColorName.put("d5869d", "dull pink");
        ColorName.put("3d0734", "aubergine");
        ColorName.put("4a0100", "mahogany");
        ColorName.put("f8481c", "reddish orange");
        ColorName.put("02590f", "deep green");
        ColorName.put("89a203", "vomit green");
        ColorName.put("e03fd8", "purple pink");
        ColorName.put("d58a94", "dusty pink");
        ColorName.put("7bb274", "faded green");
        ColorName.put("526525", "camo green");
        ColorName.put("c94cbe", "pinky purple");
        ColorName.put("db4bda", "pink purple");
        ColorName.put("9e3623", "brownish red");
        ColorName.put("b5485d", "dark rose");
        ColorName.put("735c12", "mud");
        ColorName.put("9c6d57", "brownish");
        ColorName.put("028f1e", "emerald green");
        ColorName.put("b1916e", "pale brown");
        ColorName.put("49759c", "dull blue");
        ColorName.put("a0450e", "burnt umber");
        ColorName.put("39ad48", "medium green");
        ColorName.put("b66a50", "clay");
        ColorName.put("8cffdb", "light aqua");
        ColorName.put("a4be5c", "light olive green");
        ColorName.put("cb7723", "brownish orange");
        ColorName.put("05696b", "dark aqua");
        ColorName.put("ce5dae", "purplish pink");
        ColorName.put("c85a53", "dark salmon");
        ColorName.put("96ae8d", "greenish grey");
        ColorName.put("1fa774", "jade");
        ColorName.put("ac9362", "dark beige");
        ColorName.put("01a049", "emerald");
        ColorName.put("d9544d", "pale red");
        ColorName.put("fa5ff7", "light magenta");
        ColorName.put("82cafc", "sky");
        ColorName.put("acfffc", "light cyan");
        ColorName.put("fcb001", "yellow orange");
        ColorName.put("910951", "reddish purple");
        ColorName.put("fe2c54", "reddish pink");
        ColorName.put("c875c4", "orchid");
        ColorName.put("cdc50a", "dirty yellow");
        ColorName.put("fd411e", "orange red");
        ColorName.put("9a0200", "deep red");
        ColorName.put("be6400", "orange brown");
        ColorName.put("030aa7", "cobalt blue");
        ColorName.put("fe019a", "neon pink");
        ColorName.put("f7879a", "rose pink");
        ColorName.put("887191", "greyish purple");
        ColorName.put("b00149", "raspberry");
        ColorName.put("12e193", "aqua green");
        ColorName.put("fe7b7c", "salmon pink");
        ColorName.put("ff9408", "tangerine");
        ColorName.put("6a6e09", "brownish green");
        ColorName.put("8b2e16", "red brown");
        ColorName.put("696112", "greenish brown");
        ColorName.put("e17701", "pumpkin");
        ColorName.put("0a481e", "pine green");
        ColorName.put("343837", "charcoal");
        ColorName.put("ffb7ce", "baby pink");
        ColorName.put("6a79f7", "cornflower");
        ColorName.put("5d06e9", "blue violet");
        ColorName.put("3d1c02", "chocolate");
        ColorName.put("82a67d", "greyish green");
        ColorName.put("be0119", "scarlet");
        ColorName.put("c9ff27", "green yellow");
        ColorName.put("373e02", "dark olive");
        ColorName.put("a9561e", "sienna");
        ColorName.put("caa0ff", "pastel purple");
        ColorName.put("ca6641", "terracotta");
        ColorName.put("02d8e9", "aqua blue");
        ColorName.put("88b378", "sage green");
        ColorName.put("980002", "blood red");
        ColorName.put("cb0162", "deep pink");
        ColorName.put("5cac2d", "grass");
        ColorName.put("769958", "moss");
        ColorName.put("a2bffe", "pastel blue");
        ColorName.put("10a674", "bluish green");
        ColorName.put("06b48b", "green blue");
        ColorName.put("af884a", "dark tan");
        ColorName.put("0b8b87", "greenish blue");
        ColorName.put("ffa756", "pale orange");
        ColorName.put("a2a415", "vomit");
        ColorName.put("154406", "forrest green");
        ColorName.put("856798", "dark lavender");
        ColorName.put("34013f", "dark violet");
        ColorName.put("632de9", "purple blue");
        ColorName.put("0a888a", "dark cyan");
        ColorName.put("6f7632", "olive drab");
        ColorName.put("d46a7e", "pinkish");
        ColorName.put("1e488f", "cobalt");
        ColorName.put("bc13fe", "neon purple");
        ColorName.put("7ef4cc", "light turquoise");
        ColorName.put("76cd26", "apple green");
        ColorName.put("74a662", "dull green");
        ColorName.put("80013f", "wine");
        ColorName.put("b1d1fc", "powder blue");
        ColorName.put("ffffe4", "off white");
        ColorName.put("0652ff", "electric blue");
        ColorName.put("045c5a", "dark turquoise");
        ColorName.put("5729ce", "blue purple");
        ColorName.put("069af3", "azure");
        ColorName.put("ff000d", "bright red");
        ColorName.put("f10c45", "pinkish red");
        ColorName.put("5170d7", "cornflower blue");
        ColorName.put("acbf69", "light olive");
        ColorName.put("6c3461", "grape");
        ColorName.put("5e819d", "greyish blue");
        ColorName.put("601ef9", "purplish blue");
        ColorName.put("b0dd16", "yellowish green");
        ColorName.put("cdfd02", "greenish yellow");
        ColorName.put("2c6fbb", "medium blue");
        ColorName.put("c0737a", "dusty rose");
        ColorName.put("d6b4fc", "light violet");
        ColorName.put("020035", "midnight blue");
        ColorName.put("703be7", "bluish purple");
        ColorName.put("fd3c06", "red orange");
        ColorName.put("960056", "dark magenta");
        ColorName.put("40a368", "greenish");
        ColorName.put("03719c", "ocean blue");
        ColorName.put("fc5a50", "coral");
        ColorName.put("ffffc2", "cream");
        ColorName.put("7f2b0a", "reddish brown");
        ColorName.put("b04e0f", "burnt sienna");
        ColorName.put("a03623", "brick");
        ColorName.put("87ae73", "sage");
        ColorName.put("789b73", "grey green");
        ColorName.put("ffffff", "white");
        ColorName.put("98eff9", "robin's egg blue");
        ColorName.put("658b38", "moss green");
        ColorName.put("5a7d9a", "steel blue");
        ColorName.put("380835", "eggplant");
        ColorName.put("fffe7a", "light yellow");
        ColorName.put("5ca904", "leaf green");
        ColorName.put("d8dcd6", "light grey");
        ColorName.put("a5a502", "puke");
        ColorName.put("d648d7", "pinkish purple");
        ColorName.put("047495", "sea blue");
        ColorName.put("b790d4", "pale purple");
        ColorName.put("5b7c99", "slate blue");
        ColorName.put("607c8e", "blue grey");
        ColorName.put("0b4008", "hunter green");
        ColorName.put("ed0dd9", "fuchsia");
        ColorName.put("8c000f", "crimson");
        ColorName.put("ffff84", "pale yellow");
        ColorName.put("bf9005", "ochre");
        ColorName.put("d2bd0a", "mustard yellow");
        ColorName.put("ff474c", "light red");
        ColorName.put("0485d1", "cerulean");
        ColorName.put("ffcfdc", "pale pink");
        ColorName.put("040273", "deep blue");
        ColorName.put("a83c09", "rust");
        ColorName.put("90e4c1", "light teal");
        ColorName.put("516572", "slate");
        ColorName.put("fac205", "goldenrod");
        ColorName.put("d5b60a", "dark yellow");
        ColorName.put("363737", "dark grey");
        ColorName.put("4b5d16", "army green");
        ColorName.put("6b8ba4", "grey blue");
        ColorName.put("80f9ad", "seafoam");
        ColorName.put("a57e52", "puce");
        ColorName.put("a9f971", "spring green");
        ColorName.put("c65102", "dark orange");
        ColorName.put("e2ca76", "sand");
        ColorName.put("b0ff9d", "pastel green");
        ColorName.put("9ffeb0", "mint");
        ColorName.put("fdaa48", "light orange");
        ColorName.put("fe01b1", "bright pink");
        ColorName.put("c1f80a", "chartreuse");
        ColorName.put("36013f", "deep purple");
        ColorName.put("341c02", "dark brown");
        ColorName.put("b9a281", "taupe");
        ColorName.put("8eab12", "pea green");
        ColorName.put("9aae07", "puke green");
        ColorName.put("02ab2e", "kelly green");
        ColorName.put("7af9ab", "seafoam green");
        ColorName.put("137e6d", "blue green");
        ColorName.put("aaa662", "khaki");
        ColorName.put("610023", "burgundy");
        ColorName.put("014d4e", "dark teal");
        ColorName.put("8f1402", "brick red");
        ColorName.put("4b006e", "royal purple");
        ColorName.put("580f41", "plum");
        ColorName.put("8fff9f", "mint green");
        ColorName.put("dbb40c", "gold");
        ColorName.put("a2cffe", "baby blue");
        ColorName.put("c0fb2d", "yellow green");
        ColorName.put("be03fd", "bright purple");
        ColorName.put("840000", "dark red");
        ColorName.put("d0fefe", "pale blue");
        ColorName.put("3f9b0b", "grass green");
        ColorName.put("01153e", "navy");
        ColorName.put("04d8b2", "aquamarine");
        ColorName.put("c04e01", "burnt orange");
        ColorName.put("0cff0c", "neon green");
        ColorName.put("0165fc", "bright blue");
        ColorName.put("cf6275", "rose");
        ColorName.put("ffd1df", "light pink");
        ColorName.put("ceb301", "mustard");
        ColorName.put("380282", "indigo");
        ColorName.put("aaff32", "lime");
        ColorName.put("53fca1", "sea green");
        ColorName.put("8e82fe", "periwinkle");
        ColorName.put("cb416b", "dark pink");
        ColorName.put("677a04", "olive green");
        ColorName.put("ffb07c", "peach");
        ColorName.put("c7fdb5", "pale green");
        ColorName.put("ad8150", "light brown");
        ColorName.put("ff028d", "hot pink");
        ColorName.put("000000", "black");
        ColorName.put("cea2fd", "lilac");
        ColorName.put("001146", "navy blue");
        ColorName.put("0504aa", "royal blue");
        ColorName.put("e6daa6", "beige");
        ColorName.put("ff796c", "salmon");
        ColorName.put("6e750e", "olive");
        ColorName.put("650021", "maroon");
        ColorName.put("01ff07", "bright green");
        ColorName.put("35063e", "dark purple");
        ColorName.put("ae7181", "mauve");
        ColorName.put("06470c", "forest green");
        ColorName.put("13eac9", "aqua");
        ColorName.put("00ffff", "cyan");
        ColorName.put("d1b26f", "tan");
        ColorName.put("00035b", "dark blue");
        ColorName.put("c79fef", "lavender");
        ColorName.put("06c2ac", "turquoise");
        ColorName.put("033500", "dark green");
        ColorName.put("9a0eea", "violet");
        ColorName.put("bf77f6", "light purple");
        ColorName.put("89fe05", "lime green");
        ColorName.put("929591", "grey");
        ColorName.put("75bbfd", "sky blue");
        ColorName.put("ffff14", "yellow");
        ColorName.put("c20078", "magenta");
        ColorName.put("96f97b", "light green");
        ColorName.put("f97306", "orange");
        ColorName.put("029386", "teal");
        ColorName.put("95d0fc", "light blue");
        ColorName.put("e50000", "red");
        ColorName.put("653700", "brown");
        ColorName.put("ff81c0", "pink");
        ColorName.put("0343df", "blue");
        ColorName.put("15b01a", "green");
        ColorName.put("7e1e9c", "purple");
    }

    public static HashMap<String, String> SimpleColorName = new HashMap<String, String>();
    static {
        SimpleColorName.put("ffffff", "white");
        SimpleColorName.put("000000", "black");
        SimpleColorName.put("808080", "grey");
        SimpleColorName.put("ff0000", "red");
        SimpleColorName.put("ff8080", "light red");
        SimpleColorName.put("800000", "dark red");
        SimpleColorName.put("00ff00", "green");
        SimpleColorName.put("80ff80", "light green");
        SimpleColorName.put("008000", "dark green");
        SimpleColorName.put("0000ff", "blue");
        SimpleColorName.put("8080ff", "light blue");
        SimpleColorName.put("000080", "dark blue");
        SimpleColorName.put("ffff00", "yellow");
        SimpleColorName.put("ffff80", "light yellow");
        SimpleColorName.put("7f8000", "dark yellow");
        SimpleColorName.put("ff00ff", "purple pink");
        SimpleColorName.put("ff80ff", "light purple pink");
        SimpleColorName.put("80007f", "dark purple pink");
        SimpleColorName.put("00ffff", "blue green");
        SimpleColorName.put("80ffff", "light blue green");
        SimpleColorName.put("007f80", "dark blue green");
    }

    public static String getColorFromRGB(int r, int g, int b, boolean mode) {
        String RGBHex = Integer.toHexString(r) + Integer.toHexString(g) + Integer.toHexString(b);
        RGBHex = RGBHex.toUpperCase(Locale.ROOT);
        if (!mode) {
            if (ColorName.containsKey(RGBHex)) {
                return ColorName.get(RGBHex);
            } else {
                return getNearestColor(r, g, b, false);
            }
        } else {
            if (SimpleColorName.containsKey(RGBHex)) {
                return SimpleColorName.get(RGBHex);
            } else {
                return getNearestColor(r, g, b, true);
            }
        }
    }

    public static String getNearestColor(int r, int g, int b, boolean mode) {
        String chosenKey = null;
        double minDistance = 0.0;
        boolean flag = false;
        if (!mode) {
            for (String getKey: ColorName.keySet()) {
                int key_r = convertUpperHextoInt(getKey.substring(0,2));
                int key_g = convertUpperHextoInt(getKey.substring(2,4));
                int key_b = convertUpperHextoInt(getKey.substring(4,6));
                double distance = ColorDistance(r, g, b, key_r, key_g, key_b);
                if (!flag) { // the first distance calculated
                    minDistance = distance;
                    chosenKey = getKey;
                    flag = true;
                } else {
                    if (distance < minDistance) {
                        minDistance = distance;
                        chosenKey = getKey;
                    }
                }
            }
            return ColorName.get(chosenKey);
        } else {
            for (String getKey: SimpleColorName.keySet()) {
                int key_r = convertUpperHextoInt(getKey.substring(0,2));
                int key_g = convertUpperHextoInt(getKey.substring(2,4));
                int key_b = convertUpperHextoInt(getKey.substring(4,6));
                double distance = ColorDistance(r, g, b, key_r, key_g, key_b);
                if (!flag) { // the first distance calculated
                    minDistance = distance;
                    chosenKey = getKey;
                    flag = true;
                } else {
                    if (distance < minDistance) {
                        minDistance = distance;
                        chosenKey = getKey;
                    }
                }
            }
            return SimpleColorName.get(chosenKey);
        }
    }

    /** Reference: http://www.easyrgb.com/en/math.php */
    public static double ColorDistance(int R1, int G1, int B1, int R2, int G2, int B2) {
        // convert sRGB to XYZ
        double var_R1 = R1 / 255.0;
        double var_G1 = G1 / 255.0;
        double var_B1 = B1 / 255.0;
        double var_R2 = R2 / 255.0;
        double var_G2 = G2 / 255.0;
        double var_B2 = B2 / 255.0;
        if (var_R1 > 0.04045) var_R1 = Math.pow((var_R1 + 0.055) / 1.055, 2.4);
        else                  var_R1 = var_R1 / 12.92;
        if (var_G1 > 0.04045) var_G1 = Math.pow(( var_G1 + 0.055) / 1.055, 2.4);
        else                  var_G1 = var_G1 / 12.92;
        if (var_B1 > 0.04045) var_B1 = Math.pow((var_B1 + 0.055) / 1.055, 2.4);
        else                  var_B1 = var_B1 / 12.92;
        if (var_R2 > 0.04045) var_R2 = Math.pow((var_R2 + 0.055) / 1.055, 2.4);
        else                  var_R2 = var_R2 / 12.92;
        if (var_G2 > 0.04045) var_G2 = Math.pow(( var_G2 + 0.055) / 1.055, 2.4);
        else                  var_G2 = var_G2 / 12.92;
        if (var_B2 > 0.04045) var_B2 = Math.pow((var_B2 + 0.055) / 1.055, 2.4);
        else                  var_B2 = var_B2 / 12.92;
        var_R1 = var_R1 * 100;
        var_G1 = var_G1 * 100;
        var_B1 = var_B1 * 100;
        var_R2 = var_R2 * 100;
        var_G2 = var_G2 * 100;
        var_B2 = var_B2 * 100;
        double X1 = var_R1 * 0.4124 + var_G1 * 0.3576 + var_B1 * 0.1805;
        double Y1 = var_R1 * 0.2126 + var_G1 * 0.7152 + var_B1 * 0.0722;
        double Z1 = var_R1 * 0.0193 + var_G1 * 0.1192 + var_B1 * 0.9505;
        double X2 = var_R2 * 0.4124 + var_G2 * 0.3576 + var_B2 * 0.1805;
        double Y2 = var_R2 * 0.2126 + var_G2 * 0.7152 + var_B2 * 0.0722;
        double Z2 = var_R2 * 0.0193 + var_G2 * 0.1192 + var_B2 * 0.9505;
        if (!flag) {
            Log.i("Camera", "X: " + String.valueOf(X1) + ", Y: " + String.valueOf(Y1)
                    + ", Z: " + String.valueOf(Z1));
        }
        // convert XYZ to LAB
        double referenceX = 94.791;
        double referenceY = 100.0;
        double referenceZ = 103.191;
        double var_X1 = X1 / referenceX;
        double var_Y1 = Y1 / referenceY;
        double var_Z1 = Z1 / referenceZ;
        double var_X2 = X2 / referenceX;
        double var_Y2 = Y2 / referenceY;
        double var_Z2 = Z2 / referenceZ;
        if (var_X1 > 0.008856) var_X1 = Math.pow(var_X1, 1.0 / 3);
        else                   var_X1 = 7.787 * var_X1 + 16.0 / 116;
        if (var_Y1 > 0.008856) var_Y1 = Math.pow(var_Y1, 1.0 / 3);
        else                   var_Y1 = 7.787 * var_Y1 + 16.0 / 116;
        if (var_Z1 > 0.008856) var_Z1 = Math.pow(var_Z1, 1.0 / 3);
        else                   var_Z1 = 7.787 * var_Z1 + 16.0 / 116;
        if (var_X2 > 0.008856) var_X2 = Math.pow(var_X2, 1.0 / 3);
        else                   var_X2 = 7.787 * var_X2 + 16.0 / 116;
        if (var_Y2 > 0.008856) var_Y2 = Math.pow(var_Y2, 1.0 / 3);
        else                   var_Y2 = 7.787 * var_Y2 + 16.0 / 116;
        if (var_Z2 > 0.008856) var_Z2 = Math.pow(var_Z2, 1.0 / 3);
        else                   var_Z2 = 7.787 * var_Z2 + 16.0 / 116;
        double L1 = 116 * var_Y1 - 16;
        double a1 = 500 * (var_X1 - var_Y1);
        double b1 = 200 * (var_Y1 - var_Z1);
        double L2 = 116 * var_Y2 - 16;
        double a2 = 500 * (var_X2 - var_Y2);
        double b2 = 200 * (var_Y2 - var_Z2);
        if (!flag) {
            Log.i("Camera", "L: " + String.valueOf(L1) + ", a: " + String.valueOf(a1)
                    + ", b: " + String.valueOf(b1));
            flag = true;
        }
        // Calculate distance between two Lab colors
        // reference: https://en.wikipedia.org/wiki/Color_difference#CIE94
        double WhtL = 1.0;
        double WhtC = 1.0;
        double WhtH = 1.0;
        double xDL = L1 - L2;
        double xC1 = Math.pow(a1 * a1 + b1 * b1 , 0.5);
        double xC2 = Math.pow(a2 * a2 + b2 * b2 , 0.5);
        double xDC = xC1 - xC2;
//        double xDE = Math.pow(Math.pow(L1 - L2, 2) + Math.pow(a1 - a2, 2) + Math.pow(b1 - b2, 2) , 0.5);
//        double xDH = xDE * xDE - xDL * xDL - xDC * xDC;
        double xDH = Math.pow(Math.pow(a1 - a2, 2) + Math.pow(b1 - b2, 2) - Math.pow(xDC, 2), 0.5);
//        if ( xDH > 0 ) {
//            xDH = Math.pow(xDH, 0.5);
//        } else {
//            xDH = 0;
//        }
        double xSC = 1 + 0.045 * xC1;
        double xSH = 1 + 0.015 * xC1;
        xDL /= WhtL;
        xDC /= WhtC * xSC;
        xDH /= WhtH * xSH;
        double distance = Math.pow(xDL * xDL + xDC * xDC + xDH * xDH, 0.5);
        return distance;
    }

    /** In the hashmap database, the color is provided in form like "FFFFFF".
     * Thus, we need to divide the String into 3 parts and convert them like: FF -> ff -> 255*/
    private static int convertUpperHextoInt(String x) {
        x = x.toLowerCase(Locale.ROOT);
        return Integer.parseInt(x,16);
    }
}
